-- MySQL 建表脚本：使用 mysql Profile 时在库中手工执行，或将 initialization-mode 设为 always 并指向本文件。
CREATE TABLE IF NOT EXISTS uav (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    frame_sn VARCHAR(64) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    manufacturer VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'IDLE',
    max_flight_altitude INTEGER,
    max_flight_speed INTEGER,
    flight_duration INTEGER,
    battery_capacity INTEGER,
    payload_capacity INTEGER,
    total_flight_hours INTEGER,
    last_flight_time DATETIME,
    total_flight_count INTEGER,
    first_use_date DATE,
    last_maintenance_date DATE,
    next_maintenance_date DATE,
    maintenance_interval INTEGER,
    notes VARCHAR(512),
    ai_attributes JSON,
    ai_generation_status VARCHAR(32) NOT NULL,
    ai_last_error VARCHAR(512),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_uav_frame_sn (frame_sn),
    KEY idx_uav_model (model_name),
    KEY idx_uav_manufacturer (manufacturer),
    KEY idx_uav_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;